sonar.projectKey=hitachi-developers_gauravshahfromnepal-repo_88ffa0cb-b9cb-404e-84ab-1d689404cc2e
sonar.working.directory=/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/.sonarqube/out/.sonar
sonar.projectBaseDir=/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp
sonar.pullrequest.cache.basepath=/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp

F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.projectKey=hitachi-developers_gauravshahfromnepal-repo_88ffa0cb-b9cb-404e-84ab-1d689404cc2e:F9399FF0-09E6-4E62-B159-C3C737452D6C
F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.projectName=MyFirstDotNetApp
F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.projectBaseDir=/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp
F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.sourceEncoding=utf-8
F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.tests=
F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.sources=\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/Calculator.cs",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/Program.cs",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/SonarQubeDemo.cs",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/.gitignore",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/coverage.opencover.xml",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/coverage.xml",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/obj/project.assets.json",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/obj/MyFirstDotNetApp.csproj.nuget.dgspec.json",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/obj/Debug/net10.0/MyFirstDotNetApp.sourcelink.json",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/bin/Debug/net10.0/MyFirstDotNetApp.deps.json",\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/bin/Debug/net10.0/MyFirstDotNetApp.runtimeconfig.json"

F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.cs.analyzer.projectOutPaths=\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/.sonarqube/out/0"
F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.cs.roslyn.reportFilePaths=\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/.sonarqube/out/0/Issues.json"
F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.cs.scanner.telemetry=\
"/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/.sonarqube/out/0/Telemetry.json"

F9399FF0-09E6-4E62-B159-C3C737452D6C.sonar.working.directory=/home/shahgnp/startsml_work_dir/hitachi/developer/section7/part1/MyFirstDotNetApp/.sonarqube/out/.sonar/mod0
sonar.host.url=https://sonarqube.startsml.com
sonar.scanner.skipJreProvisioning=true
sonar.cs.opencover.reportsPaths=coverage.xml
sonar.exclusions=coverage.xml
sonar.visualstudio.enable=false

sonar.modules=F9399FF0-09E6-4E62-B159-C3C737452D6C

